/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "secondary-fixed": "#d7e3ff",
              "on-primary": "#003737",
              "on-tertiary": "#383100",
              "inverse-surface": "#dbe4e3",
              "primary-fixed-dim": "#00dddd",
              "on-primary-container": "#007070",
              "inverse-primary": "#006a6a",
              "surface-container": "#192121",
              "on-surface-variant": "#b9cac9",
              "secondary-container": "#438fff",
              "surface-bright": "#323b3b",
              "on-secondary-fixed-variant": "#00458f",
              "on-error": "#690005",
              "on-secondary": "#002f65",
              "tertiary": "#ffffff",
              "primary": "#ffffff",
              "surface-dim": "#0d1515",
              "tertiary-container": "#fce442",
              "surface-container-high": "#232c2b",
              "tertiary-fixed": "#fce442",
              "error": "#ffb4ab",
              "outline": "#839493",
              "background": "#0d1515",
              "secondary": "#abc7ff",
              "surface-container-lowest": "#071010",
              "on-surface": "#dbe4e3",
              "on-secondary-fixed": "#001b3f",
              "secondary-fixed-dim": "#abc7ff",
              "on-secondary-container": "#002959",
              "primary-fixed": "#00fbfb",
              "on-background": "#dbe4e3",
              "inverse-on-surface": "#293232",
              "surface-container-low": "#151d1d",
              "on-primary-fixed": "#002020",
              "on-error-container": "#ffdad6",
              "on-tertiary-fixed-variant": "#504700",
              "primary-container": "#00fbfb",
              "surface-tint": "#00dddd",
              "surface": "#0d1515",
              "error-container": "#93000a",
              "on-tertiary-container": "#716500",
              "outline-variant": "#3a4a49",
              "on-primary-fixed-variant": "#004f4f",
              "on-tertiary-fixed": "#201c00",
              "tertiary-fixed-dim": "#dec723",
              "surface-container-highest": "#2e3636",
              "surface-variant": "#2e3636"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "margin-mobile": "20px",
              "stack-sm": "8px",
              "stack-lg": "32px",
              "section-gap": "120px",
              "stack-md": "16px",
              "container-max": "1200px",
              "gutter": "24px"
      },
      "fontFamily": {
              "headline-lg": ["Sora"],
              "body-md": ["Inter"],
              "headline-sm": ["Sora"],
              "display-lg-mobile": ["Sora"],
              "headline-md": ["Sora"],
              "label-mono": ["JetBrains Mono"],
              "body-lg": ["Inter"],
              "display-lg": ["Sora"]
      },
      "fontSize": {
              "headline-lg": ["40px", {"lineHeight": "1.2", "fontWeight": "700"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
              "display-lg-mobile": ["40px", {"lineHeight": "1.1", "fontWeight": "800"}],
              "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
              "label-mono": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
}
